// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"uuid"

	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/predicate"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/tag"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/tweet"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/tweettag"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/user"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/usertweet"
	"github.com/protobuf-orm/ent/schema/field"
)

// TweetUpdate is the builder for updating Tweet entities.
type TweetUpdate struct {
	config
	hooks    []Hook
	mutation *TweetMutation
}

// Where appends a list predicates to the TweetUpdate builder.
func (_u *TweetUpdate) Where(ps ...predicate.Tweet) *TweetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetText sets the "text" field.
func (_u *TweetUpdate) SetText(v string) *TweetUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *TweetUpdate) SetNillableText(v *string) *TweetUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// AddLikedUsersIds adds the "liked_users" edge to the User entity by Ids.
func (_u *TweetUpdate) AddLikedUsersIds(ids ...int) *TweetUpdate {
	_u.mutation.AddLikedUsersIds(ids...)
	return _u
}

// AddLikedUsers adds the "liked_users" edges to the User entity.
func (_u *TweetUpdate) AddLikedUsers(v ...*User) *TweetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.AddLikedUsersIds(ids...)
}

// AddUserIds adds the "user" edge to the User entity by Ids.
func (_u *TweetUpdate) AddUserIds(ids ...int) *TweetUpdate {
	_u.mutation.AddUserIds(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *TweetUpdate) AddUser(v ...*User) *TweetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.AddUserIds(ids...)
}

// AddTagsIds adds the "tags" edge to the Tag entity by Ids.
func (_u *TweetUpdate) AddTagsIds(ids ...int) *TweetUpdate {
	_u.mutation.AddTagsIds(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *TweetUpdate) AddTags(v ...*Tag) *TweetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.AddTagsIds(ids...)
}

// AddTweetUserIds adds the "tweet_user" edge to the UserTweet entity by Ids.
func (_u *TweetUpdate) AddTweetUserIds(ids ...int) *TweetUpdate {
	_u.mutation.AddTweetUserIds(ids...)
	return _u
}

// AddTweetUser adds the "tweet_user" edges to the UserTweet entity.
func (_u *TweetUpdate) AddTweetUser(v ...*UserTweet) *TweetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.AddTweetUserIds(ids...)
}

// AddTweetTagsIds adds the "tweet_tags" edge to the TweetTag entity by Ids.
func (_u *TweetUpdate) AddTweetTagsIds(ids ...uuid.UUID) *TweetUpdate {
	_u.mutation.AddTweetTagsIds(ids...)
	return _u
}

// AddTweetTags adds the "tweet_tags" edges to the TweetTag entity.
func (_u *TweetUpdate) AddTweetTags(v ...*TweetTag) *TweetUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.AddTweetTagsIds(ids...)
}

// Mutation returns the TweetMutation object of the builder.
func (_u *TweetUpdate) Mutation() *TweetMutation {
	return _u.mutation
}

// ClearLikedUsers clears all "liked_users" edges to the User entity.
func (_u *TweetUpdate) ClearLikedUsers() *TweetUpdate {
	_u.mutation.ClearLikedUsers()
	return _u
}

// RemoveLikedUsersIds removes the "liked_users" edge to User entities by Ids.
func (_u *TweetUpdate) RemoveLikedUsersIds(ids ...int) *TweetUpdate {
	_u.mutation.RemoveLikedUsersIds(ids...)
	return _u
}

// RemoveLikedUsers removes "liked_users" edges to User entities.
func (_u *TweetUpdate) RemoveLikedUsers(v ...*User) *TweetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.RemoveLikedUsersIds(ids...)
}

// ClearUser clears all "user" edges to the User entity.
func (_u *TweetUpdate) ClearUser() *TweetUpdate {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIds removes the "user" edge to User entities by Ids.
func (_u *TweetUpdate) RemoveUserIds(ids ...int) *TweetUpdate {
	_u.mutation.RemoveUserIds(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *TweetUpdate) RemoveUser(v ...*User) *TweetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.RemoveUserIds(ids...)
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *TweetUpdate) ClearTags() *TweetUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagsIds removes the "tags" edge to Tag entities by Ids.
func (_u *TweetUpdate) RemoveTagsIds(ids ...int) *TweetUpdate {
	_u.mutation.RemoveTagsIds(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *TweetUpdate) RemoveTags(v ...*Tag) *TweetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.RemoveTagsIds(ids...)
}

// ClearTweetUser clears all "tweet_user" edges to the UserTweet entity.
func (_u *TweetUpdate) ClearTweetUser() *TweetUpdate {
	_u.mutation.ClearTweetUser()
	return _u
}

// RemoveTweetUserIds removes the "tweet_user" edge to UserTweet entities by Ids.
func (_u *TweetUpdate) RemoveTweetUserIds(ids ...int) *TweetUpdate {
	_u.mutation.RemoveTweetUserIds(ids...)
	return _u
}

// RemoveTweetUser removes "tweet_user" edges to UserTweet entities.
func (_u *TweetUpdate) RemoveTweetUser(v ...*UserTweet) *TweetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.RemoveTweetUserIds(ids...)
}

// ClearTweetTags clears all "tweet_tags" edges to the TweetTag entity.
func (_u *TweetUpdate) ClearTweetTags() *TweetUpdate {
	_u.mutation.ClearTweetTags()
	return _u
}

// RemoveTweetTagsIds removes the "tweet_tags" edge to TweetTag entities by Ids.
func (_u *TweetUpdate) RemoveTweetTagsIds(ids ...uuid.UUID) *TweetUpdate {
	_u.mutation.RemoveTweetTagsIds(ids...)
	return _u
}

// RemoveTweetTags removes "tweet_tags" edges to TweetTag entities.
func (_u *TweetUpdate) RemoveTweetTags(v ...*TweetTag) *TweetUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.RemoveTweetTagsIds(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TweetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TweetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TweetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TweetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TweetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tweet.Table, tweet.Columns, sqlgraph.NewFieldSpec(tweet.FieldId, field.TypeInt))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(tweet.FieldText, field.TypeString, value)
	}
	if _u.mutation.LikedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.LikedUsersTable,
			Columns: tweet.LikedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		createE := &TweetLikeCreate{config: _u.config, mutation: newTweetLikeMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLikedUsersIds(); len(nodes) > 0 && !_u.mutation.LikedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.LikedUsersTable,
			Columns: tweet.LikedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TweetLikeCreate{config: _u.config, mutation: newTweetLikeMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LikedUsersIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.LikedUsersTable,
			Columns: tweet.LikedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TweetLikeCreate{config: _u.config, mutation: newTweetLikeMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.UserTable,
			Columns: tweet.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		createE := &UserTweetCreate{config: _u.config, mutation: newUserTweetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIds(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.UserTable,
			Columns: tweet.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserTweetCreate{config: _u.config, mutation: newUserTweetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.UserTable,
			Columns: tweet.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserTweetCreate{config: _u.config, mutation: newUserTweetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.TagsTable,
			Columns: tweet.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tag.FieldId, field.TypeInt),
			},
		}
		createE := &TweetTagCreate{config: _u.config, mutation: newTweetTagMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.Id.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.Id)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIds(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.TagsTable,
			Columns: tweet.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tag.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TweetTagCreate{config: _u.config, mutation: newTweetTagMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.Id.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.Id)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.TagsTable,
			Columns: tweet.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tag.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TweetTagCreate{config: _u.config, mutation: newTweetTagMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.Id.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.Id)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TweetUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetUserTable,
			Columns: []string{tweet.TweetUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(usertweet.FieldId, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTweetUserIds(); len(nodes) > 0 && !_u.mutation.TweetUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetUserTable,
			Columns: []string{tweet.TweetUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(usertweet.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TweetUserIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetUserTable,
			Columns: []string{tweet.TweetUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(usertweet.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TweetTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetTagsTable,
			Columns: []string{tweet.TweetTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tweettag.FieldId, field.TypeUuid),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTweetTagsIds(); len(nodes) > 0 && !_u.mutation.TweetTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetTagsTable,
			Columns: []string{tweet.TweetTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tweettag.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TweetTagsIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetTagsTable,
			Columns: []string{tweet.TweetTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tweettag.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tweet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TweetUpdateOne is the builder for updating a single Tweet entity.
type TweetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TweetMutation
}

// SetText sets the "text" field.
func (_u *TweetUpdateOne) SetText(v string) *TweetUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *TweetUpdateOne) SetNillableText(v *string) *TweetUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// AddLikedUsersIds adds the "liked_users" edge to the User entity by Ids.
func (_u *TweetUpdateOne) AddLikedUsersIds(ids ...int) *TweetUpdateOne {
	_u.mutation.AddLikedUsersIds(ids...)
	return _u
}

// AddLikedUsers adds the "liked_users" edges to the User entity.
func (_u *TweetUpdateOne) AddLikedUsers(v ...*User) *TweetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.AddLikedUsersIds(ids...)
}

// AddUserIds adds the "user" edge to the User entity by Ids.
func (_u *TweetUpdateOne) AddUserIds(ids ...int) *TweetUpdateOne {
	_u.mutation.AddUserIds(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *TweetUpdateOne) AddUser(v ...*User) *TweetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.AddUserIds(ids...)
}

// AddTagsIds adds the "tags" edge to the Tag entity by Ids.
func (_u *TweetUpdateOne) AddTagsIds(ids ...int) *TweetUpdateOne {
	_u.mutation.AddTagsIds(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *TweetUpdateOne) AddTags(v ...*Tag) *TweetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.AddTagsIds(ids...)
}

// AddTweetUserIds adds the "tweet_user" edge to the UserTweet entity by Ids.
func (_u *TweetUpdateOne) AddTweetUserIds(ids ...int) *TweetUpdateOne {
	_u.mutation.AddTweetUserIds(ids...)
	return _u
}

// AddTweetUser adds the "tweet_user" edges to the UserTweet entity.
func (_u *TweetUpdateOne) AddTweetUser(v ...*UserTweet) *TweetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.AddTweetUserIds(ids...)
}

// AddTweetTagsIds adds the "tweet_tags" edge to the TweetTag entity by Ids.
func (_u *TweetUpdateOne) AddTweetTagsIds(ids ...uuid.UUID) *TweetUpdateOne {
	_u.mutation.AddTweetTagsIds(ids...)
	return _u
}

// AddTweetTags adds the "tweet_tags" edges to the TweetTag entity.
func (_u *TweetUpdateOne) AddTweetTags(v ...*TweetTag) *TweetUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.AddTweetTagsIds(ids...)
}

// Mutation returns the TweetMutation object of the builder.
func (_u *TweetUpdateOne) Mutation() *TweetMutation {
	return _u.mutation
}

// ClearLikedUsers clears all "liked_users" edges to the User entity.
func (_u *TweetUpdateOne) ClearLikedUsers() *TweetUpdateOne {
	_u.mutation.ClearLikedUsers()
	return _u
}

// RemoveLikedUsersIds removes the "liked_users" edge to User entities by Ids.
func (_u *TweetUpdateOne) RemoveLikedUsersIds(ids ...int) *TweetUpdateOne {
	_u.mutation.RemoveLikedUsersIds(ids...)
	return _u
}

// RemoveLikedUsers removes "liked_users" edges to User entities.
func (_u *TweetUpdateOne) RemoveLikedUsers(v ...*User) *TweetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.RemoveLikedUsersIds(ids...)
}

// ClearUser clears all "user" edges to the User entity.
func (_u *TweetUpdateOne) ClearUser() *TweetUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIds removes the "user" edge to User entities by Ids.
func (_u *TweetUpdateOne) RemoveUserIds(ids ...int) *TweetUpdateOne {
	_u.mutation.RemoveUserIds(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *TweetUpdateOne) RemoveUser(v ...*User) *TweetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.RemoveUserIds(ids...)
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *TweetUpdateOne) ClearTags() *TweetUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagsIds removes the "tags" edge to Tag entities by Ids.
func (_u *TweetUpdateOne) RemoveTagsIds(ids ...int) *TweetUpdateOne {
	_u.mutation.RemoveTagsIds(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *TweetUpdateOne) RemoveTags(v ...*Tag) *TweetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.RemoveTagsIds(ids...)
}

// ClearTweetUser clears all "tweet_user" edges to the UserTweet entity.
func (_u *TweetUpdateOne) ClearTweetUser() *TweetUpdateOne {
	_u.mutation.ClearTweetUser()
	return _u
}

// RemoveTweetUserIds removes the "tweet_user" edge to UserTweet entities by Ids.
func (_u *TweetUpdateOne) RemoveTweetUserIds(ids ...int) *TweetUpdateOne {
	_u.mutation.RemoveTweetUserIds(ids...)
	return _u
}

// RemoveTweetUser removes "tweet_user" edges to UserTweet entities.
func (_u *TweetUpdateOne) RemoveTweetUser(v ...*UserTweet) *TweetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.RemoveTweetUserIds(ids...)
}

// ClearTweetTags clears all "tweet_tags" edges to the TweetTag entity.
func (_u *TweetUpdateOne) ClearTweetTags() *TweetUpdateOne {
	_u.mutation.ClearTweetTags()
	return _u
}

// RemoveTweetTagsIds removes the "tweet_tags" edge to TweetTag entities by Ids.
func (_u *TweetUpdateOne) RemoveTweetTagsIds(ids ...uuid.UUID) *TweetUpdateOne {
	_u.mutation.RemoveTweetTagsIds(ids...)
	return _u
}

// RemoveTweetTags removes "tweet_tags" edges to TweetTag entities.
func (_u *TweetUpdateOne) RemoveTweetTags(v ...*TweetTag) *TweetUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _u.RemoveTweetTagsIds(ids...)
}

// Where appends a list predicates to the TweetUpdate builder.
func (_u *TweetUpdateOne) Where(ps ...predicate.Tweet) *TweetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TweetUpdateOne) Select(field string, fields ...string) *TweetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tweet entity.
func (_u *TweetUpdateOne) Save(ctx context.Context) (*Tweet, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TweetUpdateOne) SaveX(ctx context.Context) *Tweet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TweetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TweetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TweetUpdateOne) sqlSave(ctx context.Context) (_node *Tweet, err error) {
	_spec := sqlgraph.NewUpdateSpec(tweet.Table, tweet.Columns, sqlgraph.NewFieldSpec(tweet.FieldId, field.TypeInt))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tweet.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tweet.FieldId)
		for _, f := range fields {
			if !tweet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tweet.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(tweet.FieldText, field.TypeString, value)
	}
	if _u.mutation.LikedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.LikedUsersTable,
			Columns: tweet.LikedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		createE := &TweetLikeCreate{config: _u.config, mutation: newTweetLikeMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLikedUsersIds(); len(nodes) > 0 && !_u.mutation.LikedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.LikedUsersTable,
			Columns: tweet.LikedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TweetLikeCreate{config: _u.config, mutation: newTweetLikeMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LikedUsersIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.LikedUsersTable,
			Columns: tweet.LikedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TweetLikeCreate{config: _u.config, mutation: newTweetLikeMutation(_u.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.UserTable,
			Columns: tweet.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		createE := &UserTweetCreate{config: _u.config, mutation: newUserTweetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIds(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.UserTable,
			Columns: tweet.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserTweetCreate{config: _u.config, mutation: newUserTweetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.UserTable,
			Columns: tweet.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserTweetCreate{config: _u.config, mutation: newUserTweetMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.TagsTable,
			Columns: tweet.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tag.FieldId, field.TypeInt),
			},
		}
		createE := &TweetTagCreate{config: _u.config, mutation: newTweetTagMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.Id.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.Id)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIds(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.TagsTable,
			Columns: tweet.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tag.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TweetTagCreate{config: _u.config, mutation: newTweetTagMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.Id.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.Id)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tweet.TagsTable,
			Columns: tweet.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tag.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TweetTagCreate{config: _u.config, mutation: newTweetTagMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.Id.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.Id)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TweetUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetUserTable,
			Columns: []string{tweet.TweetUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(usertweet.FieldId, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTweetUserIds(); len(nodes) > 0 && !_u.mutation.TweetUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetUserTable,
			Columns: []string{tweet.TweetUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(usertweet.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TweetUserIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetUserTable,
			Columns: []string{tweet.TweetUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(usertweet.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TweetTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetTagsTable,
			Columns: []string{tweet.TweetTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tweettag.FieldId, field.TypeUuid),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTweetTagsIds(); len(nodes) > 0 && !_u.mutation.TweetTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetTagsTable,
			Columns: []string{tweet.TweetTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tweettag.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TweetTagsIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tweet.TweetTagsTable,
			Columns: []string{tweet.TweetTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tweettag.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tweet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tweet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
