// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/predicate"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/tweet"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/user"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/usertweet"
	"github.com/protobuf-orm/ent/schema/field"
)

// UserTweetUpdate is the builder for updating UserTweet entities.
type UserTweetUpdate struct {
	config
	hooks    []Hook
	mutation *UserTweetMutation
}

// Where appends a list predicates to the UserTweetUpdate builder.
func (_u *UserTweetUpdate) Where(ps ...predicate.UserTweet) *UserTweetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserTweetUpdate) SetCreatedAt(v time.Time) *UserTweetUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserTweetUpdate) SetNillableCreatedAt(v *time.Time) *UserTweetUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUserId sets the "user_id" field.
func (_u *UserTweetUpdate) SetUserId(v int) *UserTweetUpdate {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "user_id" field if the given value is not nil.
func (_u *UserTweetUpdate) SetNillableUserId(v *int) *UserTweetUpdate {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetTweetId sets the "tweet_id" field.
func (_u *UserTweetUpdate) SetTweetId(v int) *UserTweetUpdate {
	_u.mutation.SetTweetId(v)
	return _u
}

// SetNillableTweetId sets the "tweet_id" field if the given value is not nil.
func (_u *UserTweetUpdate) SetNillableTweetId(v *int) *UserTweetUpdate {
	if v != nil {
		_u.SetTweetId(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserTweetUpdate) SetUser(v *User) *UserTweetUpdate {
	return _u.SetUserId(v.Id)
}

// SetTweet sets the "tweet" edge to the Tweet entity.
func (_u *UserTweetUpdate) SetTweet(v *Tweet) *UserTweetUpdate {
	return _u.SetTweetId(v.Id)
}

// Mutation returns the UserTweetMutation object of the builder.
func (_u *UserTweetUpdate) Mutation() *UserTweetMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserTweetUpdate) ClearUser() *UserTweetUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTweet clears the "tweet" edge to the Tweet entity.
func (_u *UserTweetUpdate) ClearTweet() *UserTweetUpdate {
	_u.mutation.ClearTweet()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserTweetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTweetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserTweetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTweetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTweetUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTweet.user"`)
	}
	if _u.mutation.TweetCleared() && len(_u.mutation.TweetIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTweet.tweet"`)
	}
	return nil
}

func (_u *UserTweetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertweet.Table, usertweet.Columns, sqlgraph.NewFieldSpec(usertweet.FieldId, field.TypeInt))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(usertweet.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertweet.UserTable,
			Columns: []string{usertweet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertweet.UserTable,
			Columns: []string{usertweet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TweetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertweet.TweetTable,
			Columns: []string{usertweet.TweetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tweet.FieldId, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TweetIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertweet.TweetTable,
			Columns: []string{usertweet.TweetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tweet.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertweet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserTweetUpdateOne is the builder for updating a single UserTweet entity.
type UserTweetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserTweetMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserTweetUpdateOne) SetCreatedAt(v time.Time) *UserTweetUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserTweetUpdateOne) SetNillableCreatedAt(v *time.Time) *UserTweetUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUserId sets the "user_id" field.
func (_u *UserTweetUpdateOne) SetUserId(v int) *UserTweetUpdateOne {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "user_id" field if the given value is not nil.
func (_u *UserTweetUpdateOne) SetNillableUserId(v *int) *UserTweetUpdateOne {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetTweetId sets the "tweet_id" field.
func (_u *UserTweetUpdateOne) SetTweetId(v int) *UserTweetUpdateOne {
	_u.mutation.SetTweetId(v)
	return _u
}

// SetNillableTweetId sets the "tweet_id" field if the given value is not nil.
func (_u *UserTweetUpdateOne) SetNillableTweetId(v *int) *UserTweetUpdateOne {
	if v != nil {
		_u.SetTweetId(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserTweetUpdateOne) SetUser(v *User) *UserTweetUpdateOne {
	return _u.SetUserId(v.Id)
}

// SetTweet sets the "tweet" edge to the Tweet entity.
func (_u *UserTweetUpdateOne) SetTweet(v *Tweet) *UserTweetUpdateOne {
	return _u.SetTweetId(v.Id)
}

// Mutation returns the UserTweetMutation object of the builder.
func (_u *UserTweetUpdateOne) Mutation() *UserTweetMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserTweetUpdateOne) ClearUser() *UserTweetUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTweet clears the "tweet" edge to the Tweet entity.
func (_u *UserTweetUpdateOne) ClearTweet() *UserTweetUpdateOne {
	_u.mutation.ClearTweet()
	return _u
}

// Where appends a list predicates to the UserTweetUpdate builder.
func (_u *UserTweetUpdateOne) Where(ps ...predicate.UserTweet) *UserTweetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserTweetUpdateOne) Select(field string, fields ...string) *UserTweetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserTweet entity.
func (_u *UserTweetUpdateOne) Save(ctx context.Context) (*UserTweet, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTweetUpdateOne) SaveX(ctx context.Context) *UserTweet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserTweetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTweetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTweetUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTweet.user"`)
	}
	if _u.mutation.TweetCleared() && len(_u.mutation.TweetIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTweet.tweet"`)
	}
	return nil
}

func (_u *UserTweetUpdateOne) sqlSave(ctx context.Context) (_node *UserTweet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertweet.Table, usertweet.Columns, sqlgraph.NewFieldSpec(usertweet.FieldId, field.TypeInt))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserTweet.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertweet.FieldId)
		for _, f := range fields {
			if !usertweet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usertweet.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(usertweet.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertweet.UserTable,
			Columns: []string{usertweet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertweet.UserTable,
			Columns: []string{usertweet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TweetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertweet.TweetTable,
			Columns: []string{usertweet.TweetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tweet.FieldId, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TweetIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertweet.TweetTable,
			Columns: []string{usertweet.TweetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tweet.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserTweet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertweet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
