// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package user

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/entc/integration/json/ent/predicate"
)

// Id filters vertices based on their Id field.
func Id(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldId, id))
}

// TIsNil applies the IsNil predicate on the "t" field.
func TIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldT))
}

// TNotNil applies the NotNil predicate on the "t" field.
func TNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldT))
}

// UrlIsNil applies the IsNil predicate on the "url" field.
func UrlIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldUrl))
}

// UrlNotNil applies the NotNil predicate on the "url" field.
func UrlNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldUrl))
}

// UrlsIsNil applies the IsNil predicate on the "Urls" field.
func UrlsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldUrls))
}

// UrlsNotNil applies the NotNil predicate on the "Urls" field.
func UrlsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldUrls))
}

// RawIsNil applies the IsNil predicate on the "raw" field.
func RawIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldRaw))
}

// RawNotNil applies the NotNil predicate on the "raw" field.
func RawNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldRaw))
}

// IntsIsNil applies the IsNil predicate on the "ints" field.
func IntsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldInts))
}

// IntsNotNil applies the NotNil predicate on the "ints" field.
func IntsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldInts))
}

// FloatsIsNil applies the IsNil predicate on the "floats" field.
func FloatsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldFloats))
}

// FloatsNotNil applies the NotNil predicate on the "floats" field.
func FloatsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldFloats))
}

// StringsIsNil applies the IsNil predicate on the "strings" field.
func StringsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldStrings))
}

// StringsNotNil applies the NotNil predicate on the "strings" field.
func StringsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldStrings))
}

// IntsValidateIsNil applies the IsNil predicate on the "ints_validate" field.
func IntsValidateIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldIntsValidate))
}

// IntsValidateNotNil applies the NotNil predicate on the "ints_validate" field.
func IntsValidateNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldIntsValidate))
}

// FloatsValidateIsNil applies the IsNil predicate on the "floats_validate" field.
func FloatsValidateIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldFloatsValidate))
}

// FloatsValidateNotNil applies the NotNil predicate on the "floats_validate" field.
func FloatsValidateNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldFloatsValidate))
}

// StringsValidateIsNil applies the IsNil predicate on the "strings_validate" field.
func StringsValidateIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldStringsValidate))
}

// StringsValidateNotNil applies the NotNil predicate on the "strings_validate" field.
func StringsValidateNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldStringsValidate))
}

// AddrIsNil applies the IsNil predicate on the "addr" field.
func AddrIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAddr))
}

// AddrNotNil applies the NotNil predicate on the "addr" field.
func AddrNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAddr))
}

// UnknownIsNil applies the IsNil predicate on the "unknown" field.
func UnknownIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldUnknown))
}

// UnknownNotNil applies the NotNil predicate on the "unknown" field.
func UnknownNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldUnknown))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
