// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package street

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the street type in the database.
	Label = "street"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeCity holds the string denoting the city edge name in mutations.
	EdgeCity = "city"
	// Table holds the table name of the street in the database.
	Table = "street"
	// CityTable is the table that holds the city relation/edge.
	CityTable = "street"
	// CityInverseTable is the table name for the City entity.
	// It exists in this package in order to avoid circular dependency with the "city" package.
	CityInverseTable = "city"
	// CityColumn is the table column denoting the city relation/edge.
	CityColumn = "city_streets"
)

// Columns holds all SQL columns for street fields.
var Columns = []string{
	FieldId,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "street"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"city_streets",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Street queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCityField orders the results by city field.
func ByCityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCityStep(), sql.OrderByField(field, opts...))
	}
}
func newCityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(CityInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, true, CityTable, CityColumn),
	)
}
