// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package rental

import (
	"time"

	"github.com/google/uuid"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/entc/integration/edgefield/ent/predicate"
)

// Id filters vertices based on their Id field.
func Id(id int) predicate.Rental {
	return predicate.Rental(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id int) predicate.Rental {
	return predicate.Rental(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id int) predicate.Rental {
	return predicate.Rental(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...int) predicate.Rental {
	return predicate.Rental(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...int) predicate.Rental {
	return predicate.Rental(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id int) predicate.Rental {
	return predicate.Rental(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id int) predicate.Rental {
	return predicate.Rental(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id int) predicate.Rental {
	return predicate.Rental(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id int) predicate.Rental {
	return predicate.Rental(sql.FieldLTE(FieldId, id))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.Rental {
	return predicate.Rental(sql.FieldEQ(FieldDate, v))
}

// UserId applies equality check predicate on the "user_id" field. It's identical to UserIdEQ.
func UserId(v int) predicate.Rental {
	return predicate.Rental(sql.FieldEQ(FieldUserId, v))
}

// CarId applies equality check predicate on the "car_id" field. It's identical to CarIdEQ.
func CarId(v uuid.UUID) predicate.Rental {
	return predicate.Rental(sql.FieldEQ(FieldCarId, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.Rental {
	return predicate.Rental(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.Rental {
	return predicate.Rental(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.Rental {
	return predicate.Rental(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.Rental {
	return predicate.Rental(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.Rental {
	return predicate.Rental(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.Rental {
	return predicate.Rental(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.Rental {
	return predicate.Rental(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.Rental {
	return predicate.Rental(sql.FieldLTE(FieldDate, v))
}

// UserIdEQ applies the EQ predicate on the "user_id" field.
func UserIdEQ(v int) predicate.Rental {
	return predicate.Rental(sql.FieldEQ(FieldUserId, v))
}

// UserIdNEQ applies the NEQ predicate on the "user_id" field.
func UserIdNEQ(v int) predicate.Rental {
	return predicate.Rental(sql.FieldNEQ(FieldUserId, v))
}

// UserIdIn applies the In predicate on the "user_id" field.
func UserIdIn(vs ...int) predicate.Rental {
	return predicate.Rental(sql.FieldIn(FieldUserId, vs...))
}

// UserIdNotIn applies the NotIn predicate on the "user_id" field.
func UserIdNotIn(vs ...int) predicate.Rental {
	return predicate.Rental(sql.FieldNotIn(FieldUserId, vs...))
}

// CarIdEQ applies the EQ predicate on the "car_id" field.
func CarIdEQ(v uuid.UUID) predicate.Rental {
	return predicate.Rental(sql.FieldEQ(FieldCarId, v))
}

// CarIdNEQ applies the NEQ predicate on the "car_id" field.
func CarIdNEQ(v uuid.UUID) predicate.Rental {
	return predicate.Rental(sql.FieldNEQ(FieldCarId, v))
}

// CarIdIn applies the In predicate on the "car_id" field.
func CarIdIn(vs ...uuid.UUID) predicate.Rental {
	return predicate.Rental(sql.FieldIn(FieldCarId, vs...))
}

// CarIdNotIn applies the NotIn predicate on the "car_id" field.
func CarIdNotIn(vs ...uuid.UUID) predicate.Rental {
	return predicate.Rental(sql.FieldNotIn(FieldCarId, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Rental {
	return predicate.Rental(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Rental {
	return predicate.Rental(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCar applies the HasEdge predicate on the "car" edge.
func HasCar() predicate.Rental {
	return predicate.Rental(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, true, CarTable, CarColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCarWith applies the HasEdge predicate on the "car" edge with a given conditions (other predicates).
func HasCarWith(preds ...predicate.Car) predicate.Rental {
	return predicate.Rental(func(s *sql.Selector) {
		step := newCarStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Rental) predicate.Rental {
	return predicate.Rental(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Rental) predicate.Rental {
	return predicate.Rental(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Rental) predicate.Rental {
	return predicate.Rental(sql.NotPredicates(p))
}
