// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package api

import (
	"github.com/protobuf-orm/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the api type in the database.
	Label = "api"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// Table holds the table name of the api in the database.
	Table = "api"
)

// Columns holds all Sql columns for api fields.
var Columns = []string{
	FieldId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Api queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// comment from another template.
