// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package tweettag

import (
	"time"
	"uuid"

	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/predicate"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.TweetTag {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.TweetTagOrErr(sql.FieldEQ(FieldId, vc), err)
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.TweetTag {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.TweetTagOrErr(sql.FieldEQ(FieldId, vc), err)
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.TweetTag {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.TweetTagOrErr(sql.FieldNEQ(FieldId, vc), err)
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.TweetTag {
	var (
		err error
		vcs = make([]any, len(ids))
	)
	for i := range vcs {
		if vcs[i], err = ValueScanner.Id.Value(ids[i]); err != nil {
			break
		}
	}
	return predicate.TweetTagOrErr(sql.FieldIn(FieldId, vcs...), err)
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.TweetTag {
	var (
		err error
		vcs = make([]any, len(ids))
	)
	for i := range vcs {
		if vcs[i], err = ValueScanner.Id.Value(ids[i]); err != nil {
			break
		}
	}
	return predicate.TweetTagOrErr(sql.FieldNotIn(FieldId, vcs...), err)
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.TweetTag {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.TweetTagOrErr(sql.FieldGT(FieldId, vc), err)
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.TweetTag {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.TweetTagOrErr(sql.FieldGTE(FieldId, vc), err)
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.TweetTag {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.TweetTagOrErr(sql.FieldLT(FieldId, vc), err)
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.TweetTag {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.TweetTagOrErr(sql.FieldLTE(FieldId, vc), err)
}

// AddedAt applies equality check predicate on the "added_at" field. It's identical to AddedAtEQ.
func AddedAt(v time.Time) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldEQ(FieldAddedAt, v))
}

// TagId applies equality check predicate on the "tag_id" field. It's identical to TagIdEQ.
func TagId(v int) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldEQ(FieldTagId, v))
}

// TweetId applies equality check predicate on the "tweet_id" field. It's identical to TweetIdEQ.
func TweetId(v int) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldEQ(FieldTweetId, v))
}

// AddedAtEQ applies the EQ predicate on the "added_at" field.
func AddedAtEQ(v time.Time) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldEQ(FieldAddedAt, v))
}

// AddedAtNEQ applies the NEQ predicate on the "added_at" field.
func AddedAtNEQ(v time.Time) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldNEQ(FieldAddedAt, v))
}

// AddedAtIn applies the In predicate on the "added_at" field.
func AddedAtIn(vs ...time.Time) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldIn(FieldAddedAt, vs...))
}

// AddedAtNotIn applies the NotIn predicate on the "added_at" field.
func AddedAtNotIn(vs ...time.Time) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldNotIn(FieldAddedAt, vs...))
}

// AddedAtGT applies the GT predicate on the "added_at" field.
func AddedAtGT(v time.Time) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldGT(FieldAddedAt, v))
}

// AddedAtGTE applies the GTE predicate on the "added_at" field.
func AddedAtGTE(v time.Time) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldGTE(FieldAddedAt, v))
}

// AddedAtLT applies the LT predicate on the "added_at" field.
func AddedAtLT(v time.Time) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldLT(FieldAddedAt, v))
}

// AddedAtLTE applies the LTE predicate on the "added_at" field.
func AddedAtLTE(v time.Time) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldLTE(FieldAddedAt, v))
}

// TagIdEQ applies the EQ predicate on the "tag_id" field.
func TagIdEQ(v int) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldEQ(FieldTagId, v))
}

// TagIdNEQ applies the NEQ predicate on the "tag_id" field.
func TagIdNEQ(v int) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldNEQ(FieldTagId, v))
}

// TagIdIn applies the In predicate on the "tag_id" field.
func TagIdIn(vs ...int) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldIn(FieldTagId, vs...))
}

// TagIdNotIn applies the NotIn predicate on the "tag_id" field.
func TagIdNotIn(vs ...int) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldNotIn(FieldTagId, vs...))
}

// TweetIdEQ applies the EQ predicate on the "tweet_id" field.
func TweetIdEQ(v int) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldEQ(FieldTweetId, v))
}

// TweetIdNEQ applies the NEQ predicate on the "tweet_id" field.
func TweetIdNEQ(v int) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldNEQ(FieldTweetId, v))
}

// TweetIdIn applies the In predicate on the "tweet_id" field.
func TweetIdIn(vs ...int) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldIn(FieldTweetId, vs...))
}

// TweetIdNotIn applies the NotIn predicate on the "tweet_id" field.
func TweetIdNotIn(vs ...int) predicate.TweetTag {
	return predicate.TweetTag(sql.FieldNotIn(FieldTweetId, vs...))
}

// HasTag applies the HasEdge predicate on the "tag" edge.
func HasTag() predicate.TweetTag {
	return predicate.TweetTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, TagTable, TagColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagWith applies the HasEdge predicate on the "tag" edge with a given conditions (other predicates).
func HasTagWith(preds ...predicate.Tag) predicate.TweetTag {
	return predicate.TweetTag(func(s *sql.Selector) {
		step := newTagStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTweet applies the HasEdge predicate on the "tweet" edge.
func HasTweet() predicate.TweetTag {
	return predicate.TweetTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, TweetTable, TweetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTweetWith applies the HasEdge predicate on the "tweet" edge with a given conditions (other predicates).
func HasTweetWith(preds ...predicate.Tweet) predicate.TweetTag {
	return predicate.TweetTag(func(s *sql.Selector) {
		step := newTweetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TweetTag) predicate.TweetTag {
	return predicate.TweetTag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TweetTag) predicate.TweetTag {
	return predicate.TweetTag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TweetTag) predicate.TweetTag {
	return predicate.TweetTag(sql.NotPredicates(p))
}
