// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package edgeschema

import (
	"context"
	"errors"
	"testing"
	"time"
	"uuid"

	"github.com/protobuf-orm/ent/dialect"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/attachedfile"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/file"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/friendship"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/group"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/migrate"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/relationship"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/relationshipinfo"
	_ "github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/runtime"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/tweetlike"
	"github.com/protobuf-orm/ent/entc/integration/edgeschema/ent/user"
	"github.com/protobuf-orm/ent/entql"

	_ "github.com/ncruces/go-sqlite3/driver"
	"github.com/stretchr/testify/require"
)

func TestEdgeSchemaWithId(t *testing.T) {
	client, err := ent.Open(dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	require.NoError(t, err)
	defer client.Close()
	ctx := context.Background()
	require.NoError(t, client.Schema.Create(ctx, migrate.WithGlobalUniqueId(true)))

	// Create one.
	hub, lab := client.Group.Create().SetName("GitHub").SaveX(ctx), client.Group.Create().SetName("GitLab").SaveX(ctx)
	a8m, nat := client.User.Create().SetName("a8m").AddGroups(hub, lab, hub).SaveX(ctx), client.User.Create().SetName("nati").AddGroups(hub, hub).SaveX(ctx)
	require.Equal(t, 2, a8m.QueryGroups().CountX(ctx), "should not create duplicates")
	require.Equal(t, 1, nat.QueryGroups().CountX(ctx))

	// Create batch (ignore duplicate groups).
	foobar := client.User.CreateBulk(
		client.User.Create().SetName("foo").AddGroups(hub, lab, hub, lab),
		client.User.Create().SetName("bar").AddGroups(hub, lab, hub, hub),
	).SaveX(ctx)
	for _, u := range foobar {
		require.Equal(t, 2, u.QueryGroups().CountX(ctx))
		require.Equal(t, 2, u.QueryJoinedGroups().CountX(ctx))
		edges := u.QueryJoinedGroups().AllX(ctx)
		require.False(t, edges[0].JoinedAt.IsZero())
		require.False(t, edges[1].JoinedAt.IsZero())
	}

	err = hub.Update().AddUsers(nat).Exec(ctx)
	require.True(t, ent.IsConstraintError(err), "duplicate edge error, because edge exists with a different 'joined_at' value")
	require.ErrorContains(t, errors.Unwrap(err), "add m2m edge for table user_group: ")
	require.ErrorContains(t, errors.Unwrap(err), "UNIQUE constraint failed: user_group.user_id, user_group.group_id")

	edges := a8m.QueryJoinedGroups().AllX(ctx)
	require.Equal(t, a8m.Id, edges[0].UserId)
	require.Equal(t, hub.Id, edges[0].GroupId)
	require.False(t, edges[0].JoinedAt.IsZero())
	require.Equal(t, a8m.Id, edges[1].UserId)
	require.Equal(t, lab.Id, edges[1].GroupId)
	require.False(t, edges[1].JoinedAt.IsZero())
	require.Equal(t, hub.Id, a8m.QueryJoinedGroups().QueryGroup().FirstIdX(ctx))
	require.Equal(t, lab.Id, a8m.QueryJoinedGroups().QueryGroup().Order(ent.Desc(group.FieldId)).FirstIdX(ctx))

	edges = nat.QueryJoinedGroups().AllX(ctx)
	require.Equal(t, nat.Id, edges[0].UserId)
	require.Equal(t, hub.Id, edges[0].GroupId)
	require.False(t, edges[0].JoinedAt.IsZero())

	err = nat.Update().AddGroups(hub).Exec(ctx)
	require.True(t, ent.IsConstraintError(err), "unique constraint failed: user_groups.user_id, user_groups.group_id")

	users := client.User.Query().WithJoinedGroups(func(q *ent.UserGroupQuery) { q.WithGroup() }).AllX(ctx)
	require.Equal(t, []int{a8m.Id, nat.Id}, []int{users[0].Id, users[1].Id})
	require.Equal(t, []int{hub.Id, lab.Id}, []int{users[0].Edges.JoinedGroups[0].GroupId, users[0].Edges.JoinedGroups[1].GroupId})
	require.Equal(t, []int{hub.Id, lab.Id}, []int{users[0].Edges.JoinedGroups[0].Edges.Group.Id, users[0].Edges.JoinedGroups[1].Edges.Group.Id})
	require.Equal(t, hub.Id, users[1].Edges.JoinedGroups[0].GroupId)

	// Ignore update as we already have such edge between a8m and hub.
	client.UserGroup.Create().SetUser(a8m).SetGroup(hub).OnConflict().Ignore().ExecX(ctx)

	t1 := client.Tag.Create().SetValue("tag").SaveX(ctx)
	hub.Update().AddTags(t1).ExecX(ctx)
	require.Equal(t, 1, client.GroupTag.Query().CountX(ctx))
	hub.Update().AddTags(t1).ExecX(ctx)
	// Adding the same edge should not create duplicate, but also should not fail because the edge does
	// not have extra fields besides the relation tuple and the Id (that is generated by the database).
	require.Equal(t, 1, client.GroupTag.Query().CountX(ctx))
}

func TestEdgeSchemaCompositeId(t *testing.T) {
	client, err := ent.Open(dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	require.NoError(t, err)
	defer client.Close()
	ctx := context.Background()
	require.NoError(t, client.Schema.Create(ctx, migrate.WithGlobalUniqueId(true)))

	tweets := client.Tweet.CreateBulk(
		client.Tweet.Create().SetText("foo"),
		client.Tweet.Create().SetText("bar"),
		client.Tweet.Create().SetText("baz"),
	).SaveX(ctx)
	a8m := client.User.Create().SetName("a8m").AddLikedTweets(tweets[:2]...).SaveX(ctx)
	nat := client.User.Create().SetName("nati").AddLikedTweets(tweets[0]).SaveX(ctx)
	likes := a8m.QueryLikes().AllX(ctx)
	require.Len(t, likes, 2)
	require.Equal(t, a8m.Id, likes[0].UserId)
	require.Equal(t, tweets[0].Id, likes[0].TweetId)
	require.Equal(t, a8m.Id, likes[1].UserId)
	require.Equal(t, tweets[1].Id, likes[1].TweetId)
	ts := time.Unix(1653377090, 0)
	like := client.TweetLike.Create().SetUser(a8m).SetLikedAt(ts).SetTweet(tweets[2]).SaveX(ctx)
	require.Equal(t, a8m.Id, like.UserId)
	require.Equal(t, tweets[2].Id, like.TweetId)
	require.Equal(t, a8m.Id, like.QueryUser().OnlyIdX(ctx))
	require.Equal(t, tweets[2].Id, like.QueryTweet().OnlyIdX(ctx))
	require.Equal(t, 3, a8m.QueryLikes().CountX(ctx))
	require.Equal(t, []int{tweets[0].Id, tweets[1].Id, tweets[2].Id}, a8m.QueryLikes().QueryTweet().IdsX(ctx))
	for _, k := range []*ent.TweetLike{
		a8m.QueryLikes().Where(tweetlike.LikedAt(ts)).OnlyX(ctx),
		client.TweetLike.Query().Where(tweetlike.LikedAt(ts)).OnlyX(ctx),
		client.Tweet.Query().QueryLikes().Where(tweetlike.LikedAt(ts)).OnlyX(ctx),
		client.Tweet.Query().QueryLikes().Where(tweetlike.LikedAt(ts), tweetlike.HasUserWith(user.Name(a8m.Name))).OnlyX(ctx),
		client.User.Query().QueryLikedTweets().QueryLikes().Where(tweetlike.LikedAt(ts), tweetlike.HasUserWith(user.Name(a8m.Name))).OnlyX(ctx),
	} {
		require.Equal(t, like.UserId, k.UserId)
		require.Equal(t, like.TweetId, k.TweetId)
		require.Equal(t, like.LikedAt.Unix(), k.LikedAt.Unix())
	}
	nat = nat.Update().AddLikedTweetsIds(like.TweetId).SaveX(ctx)
	require.Equal(t, 2, nat.QueryLikes().CountX(ctx))
	require.Equal(t, 5, client.TweetLike.Query().CountX(ctx))
	require.Equal(t, 3, client.TweetLike.Query().Where(tweetlike.HasUserWith(user.Name(a8m.Name))).CountX(ctx))
	require.Equal(t, 2, client.TweetLike.Query().Where(tweetlike.HasUserWith(user.Name(nat.Name))).CountX(ctx))

	var v []struct {
		UserId int `sql:"user_id"`
		Count  int `sql:"count"`
	}
	client.TweetLike.Query().GroupBy(tweetlike.FieldUserId).Aggregate(ent.Count()).ScanX(ctx, &v)
	require.Equal(t, a8m.Id, v[0].UserId)
	require.Equal(t, 3, v[0].Count)
	require.Equal(t, nat.Id, v[1].UserId)
	require.Equal(t, 2, v[1].Count)

	// Ignore update as we already have such edge between a8m and hub.
	client.TweetLike.Create().SetUserId(like.UserId).SetTweetId(like.TweetId).OnConflict().Ignore().ExecX(ctx)
	client.TweetLike.Create().SetUserId(like.UserId).SetTweetId(like.TweetId).OnConflict().DoNothing().ExecX(ctx)

	// Clean all tweet likes and create them in batch again.
	client.TweetLike.Delete().ExecX(ctx)
	likes = client.TweetLike.CreateBulk(
		client.TweetLike.Create().SetUserId(a8m.Id).SetTweet(tweets[0]),
		client.TweetLike.Create().SetUserId(a8m.Id).SetTweet(tweets[1]),
		client.TweetLike.Create().SetUserId(nat.Id).SetTweet(tweets[1]),
		client.TweetLike.Create().SetUserId(nat.Id).SetTweet(tweets[2]),
	).SaveX(ctx)
	require.Equal(t, likes[0].UserId, a8m.Id)
	require.Equal(t, likes[0].TweetId, tweets[0].Id)
	require.NotZero(t, likes[0].LikedAt)
	require.Equal(t, likes[1].UserId, a8m.Id)
	require.Equal(t, likes[1].TweetId, tweets[1].Id)
	require.NotZero(t, likes[1].LikedAt)

	require.Equal(t, likes[2].UserId, nat.Id)
	require.Equal(t, likes[2].TweetId, tweets[1].Id)
	require.NotZero(t, likes[2].LikedAt)
	require.Equal(t, likes[3].UserId, nat.Id)
	require.Equal(t, likes[3].TweetId, tweets[2].Id)
	require.NotZero(t, likes[3].LikedAt)

	affected, err := client.TweetLike.Update().SetLikedAt(time.Now()).Save(ctx)
	require.NoError(t, err)
	require.Equal(t, client.TweetLike.Query().CountX(ctx), affected, "should update all edges (table rows)")
}

func TestEdgeSchemaDefaultId(t *testing.T) {
	client, err := ent.Open(dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	require.NoError(t, err)
	defer client.Close()
	ctx := context.Background()
	require.NoError(t, client.Schema.Create(ctx))

	tweet1 := client.Tweet.Create().SetText("foo").SaveX(ctx)
	tag1 := client.Tag.Create().SetValue("1").SaveX(ctx)
	tweet1.Update().AddTags(tag1).SaveX(ctx)
	require.Equal(t, tag1.Id, tweet1.QueryTags().OnlyIdX(ctx))
	require.NotEqual(t, uuid.Nil(), tweet1.QueryTweetTags().OnlyIdX(ctx))

	tweet2 := client.Tweet.Create().SetText("bar").AddTags(tag1).SaveX(ctx)
	require.Equal(t, tag1.Id, tweet2.QueryTags().OnlyIdX(ctx))
	require.NotEqual(t, uuid.Nil(), tweet2.QueryTweetTags().OnlyIdX(ctx))
}

func TestEdgeSchemaBidiWithId(t *testing.T) {
	client, err := ent.Open(dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	require.NoError(t, err)
	defer client.Close()
	ctx := context.Background()
	require.NoError(t, client.Schema.Create(ctx, migrate.WithGlobalUniqueId(true)))

	nat := client.User.Create().SetName("nati").SaveX(ctx)
	a8m := client.User.Create().SetName("a8m").AddFriends(nat).SaveX(ctx)
	for _, f1 := range []*ent.Friendship{
		a8m.QueryFriendships().OnlyX(ctx),
		nat.QueryFriendships().QueryFriend().QueryFriendships().OnlyX(ctx),
		client.Friendship.Query().Where(friendship.HasFriendWith(user.Name(nat.Name))).OnlyX(ctx),
	} {
		require.Equal(t, friendship.DefaultWeight, f1.Weight)
		require.False(t, f1.CreatedAt.IsZero())
		require.Equal(t, a8m.Id, f1.UserId)
		require.Equal(t, nat.Id, f1.FriendsId)
	}
	require.Equal(t, 2, client.Friendship.Query().CountX(ctx), "bidirectional edges create 2 records in the join table")
}

func TestEdgeSchemaBidiCompositeId(t *testing.T) {
	client, err := ent.Open(dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	require.NoError(t, err)
	defer client.Close()
	ctx := context.Background()
	require.NoError(t, client.Schema.Create(ctx, migrate.WithGlobalUniqueId(true)))

	u1 := client.User.Create().SetName("u1").SaveX(ctx)
	u2 := client.User.Create().SetName("u2").AddRelatives(u1).SaveX(ctx)
	u3 := client.User.Create().SetName("u3").AddRelatives(u2).SaveX(ctx)

	err = u1.Update().AddRelatives(u2).Exec(ctx)
	require.True(t, ent.IsConstraintError(err), "duplicate edge error, because edge may contain a different 'weight' value in the database")
	require.ErrorContains(t, errors.Unwrap(err), "add m2m edge for table relationship: ")
	require.ErrorContains(t, errors.Unwrap(err), "UNIQUE constraint failed: relationship.user_id, relationship.relatives_id")

	u4u5 := client.User.CreateBulk(
		client.User.Create().SetName("u4").AddRelatives(u1, u2, u3),
		client.User.Create().SetName("u5").AddRelatives(u1, u2, u3),
	).SaveX(ctx)
	for _, u := range u4u5 {
		require.Equal(t, 3, u.QueryRelatives().CountX(ctx))
		edges := u.QueryRelationship().AllX(ctx)
		require.Len(t, edges, 3)
		require.NotZero(t, edges[0].Weight)
		require.NotZero(t, edges[1].Weight)
		require.NotZero(t, edges[2].Weight)

		err := u.Update().AddRelatives(u3).Exec(ctx)
		require.True(t, ent.IsConstraintError(err), "duplicate edge error, because edge may contain a different 'weight' value in the database")
		require.ErrorContains(t, errors.Unwrap(err), "add m2m edge for table relationship: ")
		require.ErrorContains(t, errors.Unwrap(err), "UNIQUE constraint failed: relationship.user_id, relationship.relatives_id")

		// Currently, the foreign-key action is configured as "NO ACTION" rather than "CASCADE", because
		// we do not clear edge-schema records when nodes are deleted, as they are treated as real nodes
		// (with additional fields) and not just as connections. Therefore, these we clear these edges
		// before deleting the record to avoid getting constraint violation.
		u.Update().ClearRelatives().ExecX(ctx)
		client.User.DeleteOne(u).ExecX(ctx)
	}

	var v []struct {
		UserId int `sql:"user_id"`
		Count  int `sql:"count"`
	}
	client.Relationship.Query().GroupBy(relationship.FieldUserId).Aggregate(ent.Count()).ScanX(ctx, &v)
	require.EqualValues(
		t,
		[]struct{ UserId, Count int }{{u1.Id, 1}, {u2.Id, 2}, {u3.Id, 1}},
		v,
	)
	for _, r := range []int{
		u2.QueryRelationship().Where(relationship.RelativesId(u3.Id)).QueryRelative().OnlyIdX(ctx),
		u1.QueryRelatives().QueryRelationship().Where(relationship.RelativesIdNEQ(u1.Id)).QueryRelative().OnlyIdX(ctx),
		client.User.Query().Where(user.Id(u1.Id)).QueryRelatives().QueryRelationship().Where(relationship.RelativesIdNEQ(u1.Id)).QueryRelative().OnlyIdX(ctx),
	} {
		require.Equal(t, u3.Id, r)
	}

	info := client.RelationshipInfo.Create().SetText("u1->u2").SaveX(ctx)
	r1 := u1.QueryRelationship().OnlyX(ctx)
	r1.Update().SetInfo(info).ExecX(ctx)
	r2 := client.User.Query().QueryRelationship().Where(relationship.HasInfo()).WithInfo().OnlyX(ctx)
	require.Equal(t, r1.UserId, r2.UserId)
	require.Equal(t, r1.RelativesId, r2.RelativesId)
	require.Equal(t, info.Id, r2.Edges.Info.Id)
}

func TestEdgeSchemaForO2M(t *testing.T) {
	client, err := ent.Open(dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	require.NoError(t, err)
	defer client.Close()
	ctx := context.Background()
	require.NoError(t, client.Schema.Create(ctx, migrate.WithGlobalUniqueId(true)))

	t1 := client.Tweet.Create().SetText("Hello Edge Schema").SaveX(ctx)
	a8m := client.User.Create().SetName("a8m").AddTweets(t1).SaveX(ctx)
	require.Equal(t, t1.Id, a8m.QueryTweets().OnlyIdX(ctx))
	_, err = client.User.Create().SetName("nati").AddTweets(t1).Save(ctx)
	require.True(t, ent.IsConstraintError(err), "Tweet can have only one author")

	nat := client.User.Create().SetName("nati").SaveX(ctx)
	err = nat.Update().AddTweets(t1).Exec(ctx)
	require.True(t, ent.IsConstraintError(err))
	err = client.UserTweet.Create().SetUser(nat).SetTweet(t1).Exec(ctx)
	require.True(t, ent.IsConstraintError(err))

	tweets := client.Tweet.CreateBulk(
		client.Tweet.Create().SetText("t1"),
		client.Tweet.Create().SetText("t2"),
	).SaveX(ctx)
	nat.Update().AddTweets(tweets...).ExecX(ctx)
}

func TestEdgeSchemaEntQL(t *testing.T) {
	client, err := ent.Open(dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	require.NoError(t, err)
	defer client.Close()
	ctx := context.Background()
	require.NoError(t, client.Schema.Create(ctx, migrate.WithGlobalUniqueId(true)))

	tweets := client.Tweet.CreateBulk(
		client.Tweet.Create().SetText("t1"),
		client.Tweet.Create().SetText("t2"),
	).SaveX(ctx)
	nat := client.User.Create().SetName("nati").SaveX(ctx)
	a8m := client.User.Create().SetName("a8m").AddLikedTweets(tweets...).SaveX(ctx)

	// Using the regular fluent API.
	require.Equal(t, a8m.Id, client.User.Query().Where(user.HasLikes()).OnlyIdX(ctx))
	require.Equal(t, nat.Id, client.User.Query().Where(user.Not(user.HasLikes())).OnlyIdX(ctx))

	// Using EntQL.
	q1, q2 := client.User.Query(), client.User.Query()
	q1.Filter().WhereHasLikes()
	q2.Filter().Where(entql.Not(entql.HasEdge("likes")))
	require.Equal(t, a8m.Id, q1.OnlyIdX(ctx))
	require.Equal(t, nat.Id, q2.OnlyIdX(ctx))

	nat.Update().AddLikedTweets(tweets[0]).ExecX(ctx)
	// Using the regular fluent API.
	require.Equal(t, 2, client.User.Query().Where(user.HasLikesWith(tweetlike.TweetId(tweets[0].Id))).CountX(ctx))
	require.Equal(t, 1, client.User.Query().Where(user.HasLikesWith(tweetlike.TweetId(tweets[1].Id))).CountX(ctx))
	// Using EntQL.
	q1, q2 = client.User.Query(), client.User.Query()
	q1.Filter().WhereHasLikesWith(tweetlike.TweetId(tweets[0].Id))
	q2.Filter().Where(entql.HasEdgeWith("likes", entql.FieldEQ(tweetlike.FieldTweetId, tweets[0].Id)))
	require.Equal(t, 2, q1.CountX(ctx))
	require.Equal(t, 2, q2.CountX(ctx))
	q1, q2 = client.User.Query(), client.User.Query()
	q1.Filter().WhereHasLikesWith(tweetlike.TweetId(tweets[1].Id))
	q2.Filter().Where(entql.HasEdgeWith("likes", entql.FieldEQ(tweetlike.FieldTweetId, tweets[1].Id)))
	require.Equal(t, 1, q1.CountX(ctx))
	require.Equal(t, 1, q2.CountX(ctx))

	u1 := client.User.Create().SetName("u1").SaveX(ctx)
	u2 := client.User.Create().SetName("u2").AddRelatives(u1).SaveX(ctx)
	client.User.Create().SetName("u3").AddRelatives(u2).ExecX(ctx)
	require.Equal(t, 4, client.Relationship.Query().CountX(ctx))
	require.Zero(t, client.Relationship.Query().Where(relationship.HasInfo()).CountX(ctx))
	ri := client.RelationshipInfo.Create().SetText("parent").SaveX(ctx)
	rl1 := client.Relationship.Query().FirstX(ctx).Update().SetInfo(ri).SaveX(ctx)
	require.Equal(t, 1, client.Relationship.Query().Where(relationship.HasInfo()).CountX(ctx))
	// Using EntQL.
	q3 := client.Relationship.Query()
	q3.Filter().WhereHasInfoWith(relationshipinfo.Id(ri.Id))
	rl2 := q3.OnlyX(ctx)
	require.Equal(t, rl1.UserId, rl2.UserId)
	require.Equal(t, rl1.RelativesId, rl2.RelativesId)
	require.Equal(t, rl1.InfoId, rl2.InfoId)
}

func TestEdgeSchemaTypeMatching(t *testing.T) {
	client, err := ent.Open(dialect.SQLite, "file:ent?mode=memory&_fk=1")
	require.NoError(t, err)
	defer client.Close()
	ctx := context.Background()
	require.NoError(t, client.Schema.Create(ctx, migrate.WithGlobalUniqueId(true)))

	files := client.File.CreateBulk(
		client.File.Create().SetName("a"),
		client.File.Create().SetName("b"),
		client.File.Create().SetName("c"),
	).SaveX(ctx)
	proc := client.Process.Create().AddFiles(files[:2]...).SaveX(ctx)

	// Assoc query.
	require.Equal(t, []string{"a", "b"}, proc.QueryFiles().Order(ent.Asc(file.FieldName)).Select(file.FieldName).StringsX(ctx))
	require.Equal(t, []int{files[0].Id, files[1].Id}, proc.QueryAttachedFiles().Order(ent.Asc(attachedfile.FieldFId)).Select(attachedfile.FieldFId).IntsX(ctx))
	require.Equal(t, []int{files[0].Id, files[1].Id}, proc.QueryAttachedFiles().QueryFi().IdsX(ctx))
	require.Equal(t, proc.Id, client.Process.Query().QueryAttachedFiles().QueryProc().OnlyIdX(ctx))

	// Inverse query.
	require.Equal(t, proc.Id, files[0].QueryProcesses().OnlyIdX(ctx))
	require.Equal(t, proc.Id, files[1].QueryProcesses().OnlyIdX(ctx))
	require.False(t, files[2].QueryProcesses().ExistX(ctx))
	require.Equal(t, []int{files[0].Id, files[1].Id}, client.File.Query().QueryProcesses().QueryFiles().IdsX(ctx))
	require.Equal(t, []int{files[0].Id, files[1].Id}, client.File.Query().QueryProcesses().QueryAttachedFiles().QueryFi().IdsX(ctx))

	// Edge schema query and mutation.
	require.Equal(t, []int{files[0].Id, files[1].Id}, client.AttachedFile.Query().QueryFi().IdsX(ctx))
	require.Equal(t, []int{files[0].Id, files[1].Id}, client.AttachedFile.Query().QueryProc().QueryFiles().IdsX(ctx))
	require.Equal(t, proc.Id, client.AttachedFile.Query().QueryProc().OnlyIdX(ctx))
	af := client.AttachedFile.Create().SetFi(files[2]).SetProc(proc).SaveX(ctx)
	require.Equal(t, proc.Id, af.QueryProc().OnlyIdX(ctx))
	require.Equal(t, files[2].Id, af.QueryFi().OnlyIdX(ctx))
	require.Equal(t, []int{files[0].Id, files[1].Id, files[2].Id}, client.AttachedFile.Query().QueryFi().IdsX(ctx))
	require.Equal(t, files[2].Id, client.AttachedFile.Query().QueryProc().QueryFiles().Where(file.Name(files[2].Name)).OnlyIdX(ctx))
}
