// Code generated by ent, DO NOT EDIT.

package pet

import (
	"github.com/protobuf-orm/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the pet type in the database.
	Label = "pet"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the pet in the database.
	Table = "pet"
)

// Columns holds all Sql columns for pet fields.
var Columns = []string{
	FieldId,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Pet queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}
