// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"github.com/protobuf-orm/ent/dialect/sql/schema"
	"github.com/protobuf-orm/ent/schema/field"
)

var (
	// AccountColumns holds the columns for the "account" table.
	AccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeOther, SchemaType: map[string]string{"mysql": "bigint", "postgres": "bigint", "sqlite3": "integer"}},
		{Name: "email", Type: field.TypeString},
	}
	// AccountTable holds the schema information for the "account" table.
	AccountTable = &schema.Table{
		Name:       "account",
		Columns:    AccountColumns,
		PrimaryKey: []*schema.Column{AccountColumns[0]},
	}
	// BlobColumns holds the columns for the "blob" table.
	BlobColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true, Default: "uuid_generate_v4()"},
		{Name: "uuid", Type: field.TypeUUID, Unique: true},
		{Name: "count", Type: field.TypeInt, Default: 0},
		{Name: "blob_parent", Type: field.TypeUUID, Unique: true, Nullable: true},
	}
	// BlobTable holds the schema information for the "blob" table.
	BlobTable = &schema.Table{
		Name:       "blob",
		Columns:    BlobColumns,
		PrimaryKey: []*schema.Column{BlobColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "blob_blob_parent",
				Columns:    []*schema.Column{BlobColumns[3]},
				RefColumns: []*schema.Column{BlobColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// BlobLinkColumns holds the columns for the "blob_link" table.
	BlobLinkColumns = []*schema.Column{
		{Name: "created_at", Type: field.TypeTime},
		{Name: "blob_id", Type: field.TypeUUID},
		{Name: "links_id", Type: field.TypeUUID},
	}
	// BlobLinkTable holds the schema information for the "blob_link" table.
	BlobLinkTable = &schema.Table{
		Name:       "blob_link",
		Columns:    BlobLinkColumns,
		PrimaryKey: []*schema.Column{BlobLinkColumns[1], BlobLinkColumns[2]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "blob_link_blob_blob",
				Columns:    []*schema.Column{BlobLinkColumns[1]},
				RefColumns: []*schema.Column{BlobColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "blob_link_blob_link",
				Columns:    []*schema.Column{BlobLinkColumns[2]},
				RefColumns: []*schema.Column{BlobColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CarColumns holds the columns for the "car" table.
	CarColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "before_id", Type: field.TypeFloat64, Nullable: true},
		{Name: "after_id", Type: field.TypeFloat64, Nullable: true},
		{Name: "model", Type: field.TypeString},
		{Name: "pet_cars", Type: field.TypeString, Nullable: true, Size: 36},
	}
	// CarTable holds the schema information for the "car" table.
	CarTable = &schema.Table{
		Name:       "car",
		Columns:    CarColumns,
		PrimaryKey: []*schema.Column{CarColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "car_pet_cars",
				Columns:    []*schema.Column{CarColumns[4]},
				RefColumns: []*schema.Column{PetColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DeviceColumns holds the columns for the "device" table.
	DeviceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeBytes, Size: 64},
		{Name: "device_active_session", Type: field.TypeBytes, Nullable: true, Size: 64},
	}
	// DeviceTable holds the schema information for the "device" table.
	DeviceTable = &schema.Table{
		Name:       "device",
		Columns:    DeviceColumns,
		PrimaryKey: []*schema.Column{DeviceColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "device_session_active_session",
				Columns:    []*schema.Column{DeviceColumns[1]},
				RefColumns: []*schema.Column{SessionColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DocColumns holds the columns for the "doc" table.
	DocColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 36, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "text", Type: field.TypeString, Nullable: true},
		{Name: "doc_children", Type: field.TypeString, Nullable: true, Size: 36, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// DocTable holds the schema information for the "doc" table.
	DocTable = &schema.Table{
		Name:       "doc",
		Columns:    DocColumns,
		PrimaryKey: []*schema.Column{DocColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "doc_doc_children",
				Columns:    []*schema.Column{DocColumns[2]},
				RefColumns: []*schema.Column{DocColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// GroupColumns holds the columns for the "group" table.
	GroupColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// GroupTable holds the schema information for the "group" table.
	GroupTable = &schema.Table{
		Name:       "group",
		Columns:    GroupColumns,
		PrimaryKey: []*schema.Column{GroupColumns[0]},
	}
	// IntSidColumns holds the columns for the "int_sid" table.
	IntSidColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "int_sid_parent", Type: field.TypeInt64, Nullable: true},
	}
	// IntSidTable holds the schema information for the "int_sid" table.
	IntSidTable = &schema.Table{
		Name:       "int_sid",
		Columns:    IntSidColumns,
		PrimaryKey: []*schema.Column{IntSidColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "int_sid_int_sid_parent",
				Columns:    []*schema.Column{IntSidColumns[1]},
				RefColumns: []*schema.Column{IntSidColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// LinkColumns holds the columns for the "link" table.
	LinkColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "link_information", Type: field.TypeJSON},
	}
	// LinkTable holds the schema information for the "link" table.
	LinkTable = &schema.Table{
		Name:       "link",
		Columns:    LinkColumns,
		PrimaryKey: []*schema.Column{LinkColumns[0]},
	}
	// MixinIDColumns holds the columns for the "mixin_id" table.
	MixinIDColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "some_field", Type: field.TypeString},
		{Name: "mixin_field", Type: field.TypeString},
	}
	// MixinIDTable holds the schema information for the "mixin_id" table.
	MixinIDTable = &schema.Table{
		Name:       "mixin_id",
		Columns:    MixinIDColumns,
		PrimaryKey: []*schema.Column{MixinIDColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mixinid_id",
				Unique:  false,
				Columns: []*schema.Column{MixinIDColumns[0]},
			},
			{
				Name:    "mixinid_id_some_field",
				Unique:  false,
				Columns: []*schema.Column{MixinIDColumns[0], MixinIDColumns[1]},
			},
			{
				Name:    "mixinid_id_mixin_field",
				Unique:  false,
				Columns: []*schema.Column{MixinIDColumns[0], MixinIDColumns[2]},
			},
			{
				Name:    "mixinid_id_mixin_field_some_field",
				Unique:  false,
				Columns: []*schema.Column{MixinIDColumns[0], MixinIDColumns[2], MixinIDColumns[1]},
			},
		},
	}
	// NoteColumns holds the columns for the "note" table.
	NoteColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 36},
		{Name: "text", Type: field.TypeString, Nullable: true},
		{Name: "note_children", Type: field.TypeString, Nullable: true, Size: 36},
	}
	// NoteTable holds the schema information for the "note" table.
	NoteTable = &schema.Table{
		Name:       "note",
		Columns:    NoteColumns,
		PrimaryKey: []*schema.Column{NoteColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "note_note_children",
				Columns:    []*schema.Column{NoteColumns[2]},
				RefColumns: []*schema.Column{NoteColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OtherColumns holds the columns for the "other" table.
	OtherColumns = []*schema.Column{
		{Name: "id", Type: field.TypeOther, SchemaType: map[string]string{"mysql": "bigint", "postgres": "bigint", "sqlite3": "integer"}},
	}
	// OtherTable holds the schema information for the "other" table.
	OtherTable = &schema.Table{
		Name:       "other",
		Columns:    OtherColumns,
		PrimaryKey: []*schema.Column{OtherColumns[0]},
	}
	// PetColumns holds the columns for the "pet" table.
	PetColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 36},
		{Name: "pet_best_friend", Type: field.TypeString, Unique: true, Nullable: true, Size: 36},
		{Name: "user_pets", Type: field.TypeInt, Nullable: true},
	}
	// PetTable holds the schema information for the "pet" table.
	PetTable = &schema.Table{
		Name:       "pet",
		Columns:    PetColumns,
		PrimaryKey: []*schema.Column{PetColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pet_pet_best_friend",
				Columns:    []*schema.Column{PetColumns[1]},
				RefColumns: []*schema.Column{PetColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "pet_user_pets",
				Columns:    []*schema.Column{PetColumns[2]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RevisionColumns holds the columns for the "revision" table.
	RevisionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
	}
	// RevisionTable holds the schema information for the "revision" table.
	RevisionTable = &schema.Table{
		Name:       "revision",
		Columns:    RevisionColumns,
		PrimaryKey: []*schema.Column{RevisionColumns[0]},
	}
	// SessionColumns holds the columns for the "session" table.
	SessionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeBytes, Size: 64},
		{Name: "device_sessions", Type: field.TypeBytes, Nullable: true, Size: 64},
	}
	// SessionTable holds the schema information for the "session" table.
	SessionTable = &schema.Table{
		Name:       "session",
		Columns:    SessionColumns,
		PrimaryKey: []*schema.Column{SessionColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "session_device_sessions",
				Columns:    []*schema.Column{SessionColumns[1]},
				RefColumns: []*schema.Column{DeviceColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TokenColumns holds the columns for the "token" table.
	TokenColumns = []*schema.Column{
		{Name: "id", Type: field.TypeOther, SchemaType: map[string]string{"mysql": "bigint", "postgres": "bigint", "sqlite3": "integer"}},
		{Name: "body", Type: field.TypeString},
		{Name: "account_token", Type: field.TypeOther, SchemaType: map[string]string{"mysql": "bigint", "postgres": "bigint", "sqlite3": "integer"}},
	}
	// TokenTable holds the schema information for the "token" table.
	TokenTable = &schema.Table{
		Name:       "token",
		Columns:    TokenColumns,
		PrimaryKey: []*schema.Column{TokenColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "token_account_token",
				Columns:    []*schema.Column{TokenColumns[2]},
				RefColumns: []*schema.Column{AccountColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeInt, Increment: true},
		{Name: "user_children", Type: field.TypeInt, Nullable: true},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_user_children",
				Columns:    []*schema.Column{UserColumns[1]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ValueScanColumns holds the columns for the "value_scan" table.
	ValueScanColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// ValueScanTable holds the schema information for the "value_scan" table.
	ValueScanTable = &schema.Table{
		Name:       "value_scan",
		Columns:    ValueScanColumns,
		PrimaryKey: []*schema.Column{ValueScanColumns[0]},
	}
	// DocRelatedColumns holds the columns for the "doc_related" table.
	DocRelatedColumns = []*schema.Column{
		{Name: "doc_id", Type: field.TypeString, Size: 36, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "related_id", Type: field.TypeString, Size: 36, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// DocRelatedTable holds the schema information for the "doc_related" table.
	DocRelatedTable = &schema.Table{
		Name:       "doc_related",
		Columns:    DocRelatedColumns,
		PrimaryKey: []*schema.Column{DocRelatedColumns[0], DocRelatedColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "doc_related_doc_id",
				Columns:    []*schema.Column{DocRelatedColumns[0]},
				RefColumns: []*schema.Column{DocColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "doc_related_related_id",
				Columns:    []*schema.Column{DocRelatedColumns[1]},
				RefColumns: []*schema.Column{DocColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// GroupUsersColumns holds the columns for the "group_users" table.
	GroupUsersColumns = []*schema.Column{
		{Name: "group_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// GroupUsersTable holds the schema information for the "group_users" table.
	GroupUsersTable = &schema.Table{
		Name:       "group_users",
		Columns:    GroupUsersColumns,
		PrimaryKey: []*schema.Column{GroupUsersColumns[0], GroupUsersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_users_group_id",
				Columns:    []*schema.Column{GroupUsersColumns[0]},
				RefColumns: []*schema.Column{GroupColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "group_users_user_id",
				Columns:    []*schema.Column{GroupUsersColumns[1]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PetFriendsColumns holds the columns for the "pet_friends" table.
	PetFriendsColumns = []*schema.Column{
		{Name: "pet_id", Type: field.TypeString, Size: 36},
		{Name: "friends_id", Type: field.TypeString, Size: 36},
	}
	// PetFriendsTable holds the schema information for the "pet_friends" table.
	PetFriendsTable = &schema.Table{
		Name:       "pet_friends",
		Columns:    PetFriendsColumns,
		PrimaryKey: []*schema.Column{PetFriendsColumns[0], PetFriendsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pet_friends_pet_id",
				Columns:    []*schema.Column{PetFriendsColumns[0]},
				RefColumns: []*schema.Column{PetColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "pet_friends_friends_id",
				Columns:    []*schema.Column{PetFriendsColumns[1]},
				RefColumns: []*schema.Column{PetColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountTable,
		BlobTable,
		BlobLinkTable,
		CarTable,
		DeviceTable,
		DocTable,
		GroupTable,
		IntSidTable,
		LinkTable,
		MixinIDTable,
		NoteTable,
		OtherTable,
		PetTable,
		RevisionTable,
		SessionTable,
		TokenTable,
		UserTable,
		ValueScanTable,
		DocRelatedTable,
		GroupUsersTable,
		PetFriendsTable,
	}
)

func init() {
	BlobTable.ForeignKeys[0].RefTable = BlobTable
	BlobLinkTable.ForeignKeys[0].RefTable = BlobTable
	BlobLinkTable.ForeignKeys[1].RefTable = BlobTable
	CarTable.ForeignKeys[0].RefTable = PetTable
	DeviceTable.ForeignKeys[0].RefTable = SessionTable
	DocTable.ForeignKeys[0].RefTable = DocTable
	IntSidTable.ForeignKeys[0].RefTable = IntSidTable
	NoteTable.ForeignKeys[0].RefTable = NoteTable
	PetTable.ForeignKeys[0].RefTable = PetTable
	PetTable.ForeignKeys[1].RefTable = UserTable
	SessionTable.ForeignKeys[0].RefTable = DeviceTable
	TokenTable.ForeignKeys[0].RefTable = AccountTable
	UserTable.ForeignKeys[0].RefTable = UserTable
	DocRelatedTable.ForeignKeys[0].RefTable = DocTable
	DocRelatedTable.ForeignKeys[1].RefTable = DocTable
	GroupUsersTable.ForeignKeys[0].RefTable = GroupTable
	GroupUsersTable.ForeignKeys[1].RefTable = UserTable
	PetFriendsTable.ForeignKeys[0].RefTable = PetTable
	PetFriendsTable.ForeignKeys[1].RefTable = PetTable
}
