// Copyright 2026 Seunghyun Hwang. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package ent

//go:generate go run -mod=mod github.com/protobuf-orm/ent/cmd/ent generate --feature sql/no-client-schema --header "// Copyright 2026 Seunghyun Hwang. All rights reserved.\n// This source code is licensed under the Apache 2.0 license found\n// in the LICENSE file in the root directory of this source tree.\n\n// Code generated by ent, DO NOT EDIT." ./schema
