// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package car

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/entc/integration/migrate/entv1/predicate"
)

// Id filters vertices based on their Id field.
func Id(id int) predicate.Car {
	return predicate.Car(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id int) predicate.Car {
	return predicate.Car(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id int) predicate.Car {
	return predicate.Car(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...int) predicate.Car {
	return predicate.Car(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...int) predicate.Car {
	return predicate.Car(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id int) predicate.Car {
	return predicate.Car(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id int) predicate.Car {
	return predicate.Car(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id int) predicate.Car {
	return predicate.Car(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id int) predicate.Car {
	return predicate.Car(sql.FieldLTE(FieldId, id))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Car {
	return predicate.Car(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Car {
	return predicate.Car(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Car) predicate.Car {
	return predicate.Car(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Car) predicate.Car {
	return predicate.Car(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Car) predicate.Car {
	return predicate.Car(sql.NotPredicates(p))
}
