// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"github.com/protobuf-orm/ent/dialect/sql/schema"
	"github.com/protobuf-orm/ent/schema/field"
)

var (
	// GroupColumns holds the columns for the "group" table.
	GroupColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "Unknown"},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// GroupTable holds the schema information for the "group" table.
	GroupTable = &schema.Table{
		Name:       "group",
		Columns:    GroupColumns,
		PrimaryKey: []*schema.Column{GroupColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_tenant_tenant",
				Columns:    []*schema.Column{GroupColumns[2]},
				RefColumns: []*schema.Column{TenantColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TenantColumns holds the columns for the "tenant" table.
	TenantColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// TenantTable holds the schema information for the "tenant" table.
	TenantTable = &schema.Table{
		Name:       "tenant",
		Columns:    TenantColumns,
		PrimaryKey: []*schema.Column{TenantColumns[0]},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "Unknown"},
		{Name: "foods", Type: field.TypeJson, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_tenant_tenant",
				Columns:    []*schema.Column{UserColumns[3]},
				RefColumns: []*schema.Column{TenantColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UserGroupsColumns holds the columns for the "user_groups" table.
	UserGroupsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "group_id", Type: field.TypeInt},
	}
	// UserGroupsTable holds the schema information for the "user_groups" table.
	UserGroupsTable = &schema.Table{
		Name:       "user_groups",
		Columns:    UserGroupsColumns,
		PrimaryKey: []*schema.Column{UserGroupsColumns[0], UserGroupsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_groups_user_id",
				Columns:    []*schema.Column{UserGroupsColumns[0]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_groups_group_id",
				Columns:    []*schema.Column{UserGroupsColumns[1]},
				RefColumns: []*schema.Column{GroupColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GroupTable,
		TenantTable,
		UserTable,
		UserGroupsTable,
	}
)

func init() {
	GroupTable.ForeignKeys[0].RefTable = TenantTable
	UserTable.ForeignKeys[0].RefTable = TenantTable
	UserGroupsTable.ForeignKeys[0].RefTable = UserTable
	UserGroupsTable.ForeignKeys[1].RefTable = GroupTable
}
