// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package roleuser

import (
	"time"

	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the roleuser type in the database.
	Label = "role_user"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldRoleId holds the string denoting the role_id field in the database.
	FieldRoleId = "role_id"
	// FieldUserId holds the string denoting the user_id field in the database.
	FieldUserId = "user_id"
	// EdgeRole holds the string denoting the role edge name in mutations.
	EdgeRole = "role"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// RoleFieldId holds the string denoting the Id field of the Role.
	RoleFieldId = "id"
	// UserFieldId holds the string denoting the Id field of the User.
	UserFieldId = "id"
	// Table holds the table name of the roleuser in the database.
	Table = "role_user"
	// RoleTable is the table that holds the role relation/edge.
	RoleTable = "role_user"
	// RoleInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RoleInverseTable = "role"
	// RoleColumn is the table column denoting the role relation/edge.
	RoleColumn = "role_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "role_user"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "user"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all Sql columns for roleuser fields.
var Columns = []string{
	FieldCreatedAt,
	FieldRoleId,
	FieldUserId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RoleUser queries.
type OrderOption func(*sql.Selector)

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRoleId orders the results by the role_id field.
func ByRoleId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleId, opts...).ToFunc()
}

// ByUserId orders the results by the user_id field.
func ByUserId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserId, opts...).ToFunc()
}

// ByRoleField orders the results by role field.
func ByRoleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoleStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newRoleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, RoleColumn),
		sqlgraph.To(RoleInverseTable, RoleFieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, RoleTable, RoleColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, UserColumn),
		sqlgraph.To(UserInverseTable, UserFieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
