// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/entc/integration/edgefield/ent/car"
	"github.com/protobuf-orm/ent/entc/integration/edgefield/ent/rental"
	"github.com/protobuf-orm/ent/schema/field"
)

// CarCreate is the builder for creating a Car entity.
type CarCreate struct {
	config
	mutation *CarMutation
	hooks    []Hook
}

// SetNumber sets the "number" field.
func (_c *CarCreate) SetNumber(v string) *CarCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_c *CarCreate) SetNillableNumber(v *string) *CarCreate {
	if v != nil {
		_c.SetNumber(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *CarCreate) SetId(v uuid.UUID) *CarCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetNillableId sets the "id" field if the given value is not nil.
func (_c *CarCreate) SetNillableId(v *uuid.UUID) *CarCreate {
	if v != nil {
		_c.SetId(*v)
	}
	return _c
}

// AddRentalsIds adds the "rentals" edge to the Rental entity by Ids.
func (_c *CarCreate) AddRentalsIds(ids ...int) *CarCreate {
	_c.mutation.AddRentalsIds(ids...)
	return _c
}

// AddRentals adds the "rentals" edges to the Rental entity.
func (_c *CarCreate) AddRentals(v ...*Rental) *CarCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _c.AddRentalsIds(ids...)
}

// Mutation returns the CarMutation object of the builder.
func (_c *CarCreate) Mutation() *CarMutation {
	return _c.mutation
}

// Save creates the Car in the database.
func (_c *CarCreate) Save(ctx context.Context) (*Car, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarCreate) SaveX(ctx context.Context) *Car {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CarCreate) defaults() {
	if _, ok := _c.mutation.Id(); !ok {
		v := car.DefaultId()
		_c.mutation.SetId(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarCreate) check() error {
	return nil
}

func (_c *CarCreate) sqlSave(ctx context.Context) (*Car, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else if err := _node.Id.Scan(_spec.Id.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarCreate) createSpec() (*Car, *sqlgraph.CreateSpec) {
	var (
		_node = &Car{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(car.Table, sqlgraph.NewFieldSpec(car.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(car.FieldNumber, field.TypeString, value)
		_node.Number = value
	}
	if nodes := _c.mutation.RentalsIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   car.RentalsTable,
			Columns: []string{car.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(rental.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CarCreateBulk is the builder for creating many Car entities in bulk.
type CarCreateBulk struct {
	config
	err      error
	builders []*CarCreate
}

// Save creates the Car entities in the database.
func (_c *CarCreateBulk) Save(ctx context.Context) ([]*Car, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Car, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarCreateBulk) SaveX(ctx context.Context) []*Car {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
