// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/entc/integration/edgefield/ent/card"
	"github.com/protobuf-orm/ent/entc/integration/edgefield/ent/info"
	"github.com/protobuf-orm/ent/entc/integration/edgefield/ent/metadata"
	"github.com/protobuf-orm/ent/entc/integration/edgefield/ent/pet"
	"github.com/protobuf-orm/ent/entc/integration/edgefield/ent/rental"
	"github.com/protobuf-orm/ent/entc/integration/edgefield/ent/user"
	"github.com/protobuf-orm/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetParentId sets the "parent_id" field.
func (_c *UserCreate) SetParentId(v int) *UserCreate {
	_c.mutation.SetParentId(v)
	return _c
}

// SetNillableParentId sets the "parent_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableParentId(v *int) *UserCreate {
	if v != nil {
		_c.SetParentId(*v)
	}
	return _c
}

// SetSpouseId sets the "spouse_id" field.
func (_c *UserCreate) SetSpouseId(v int) *UserCreate {
	_c.mutation.SetSpouseId(v)
	return _c
}

// SetNillableSpouseId sets the "spouse_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableSpouseId(v *int) *UserCreate {
	if v != nil {
		_c.SetSpouseId(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *UserCreate) SetId(v int) *UserCreate {
	_c.mutation.SetId(v)
	return _c
}

// AddPetsIds adds the "pets" edge to the Pet entity by Ids.
func (_c *UserCreate) AddPetsIds(ids ...int) *UserCreate {
	_c.mutation.AddPetsIds(ids...)
	return _c
}

// AddPets adds the "pets" edges to the Pet entity.
func (_c *UserCreate) AddPets(v ...*Pet) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _c.AddPetsIds(ids...)
}

// SetParent sets the "parent" edge to the User entity.
func (_c *UserCreate) SetParent(v *User) *UserCreate {
	return _c.SetParentId(v.Id)
}

// AddChildrenIds adds the "children" edge to the User entity by Ids.
func (_c *UserCreate) AddChildrenIds(ids ...int) *UserCreate {
	_c.mutation.AddChildrenIds(ids...)
	return _c
}

// AddChildren adds the "children" edges to the User entity.
func (_c *UserCreate) AddChildren(v ...*User) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _c.AddChildrenIds(ids...)
}

// SetSpouse sets the "spouse" edge to the User entity.
func (_c *UserCreate) SetSpouse(v *User) *UserCreate {
	return _c.SetSpouseId(v.Id)
}

// SetCardId sets the "card" edge to the Card entity by Id.
func (_c *UserCreate) SetCardId(id int) *UserCreate {
	_c.mutation.SetCardId(id)
	return _c
}

// SetNillableCardId sets the "card" edge to the Card entity by Id if the given value is not nil.
func (_c *UserCreate) SetNillableCardId(id *int) *UserCreate {
	if id != nil {
		_c = _c.SetCardId(*id)
	}
	return _c
}

// SetCard sets the "card" edge to the Card entity.
func (_c *UserCreate) SetCard(v *Card) *UserCreate {
	return _c.SetCardId(v.Id)
}

// SetMetadataId sets the "metadata" edge to the Metadata entity by Id.
func (_c *UserCreate) SetMetadataId(id int) *UserCreate {
	_c.mutation.SetMetadataId(id)
	return _c
}

// SetNillableMetadataId sets the "metadata" edge to the Metadata entity by Id if the given value is not nil.
func (_c *UserCreate) SetNillableMetadataId(id *int) *UserCreate {
	if id != nil {
		_c = _c.SetMetadataId(*id)
	}
	return _c
}

// SetMetadata sets the "metadata" edge to the Metadata entity.
func (_c *UserCreate) SetMetadata(v *Metadata) *UserCreate {
	return _c.SetMetadataId(v.Id)
}

// AddInfoIds adds the "info" edge to the Info entity by Ids.
func (_c *UserCreate) AddInfoIds(ids ...int) *UserCreate {
	_c.mutation.AddInfoIds(ids...)
	return _c
}

// AddInfo adds the "info" edges to the Info entity.
func (_c *UserCreate) AddInfo(v ...*Info) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _c.AddInfoIds(ids...)
}

// AddRentalsIds adds the "rentals" edge to the Rental entity by Ids.
func (_c *UserCreate) AddRentalsIds(ids ...int) *UserCreate {
	_c.mutation.AddRentalsIds(ids...)
	return _c
}

// AddRentals adds the "rentals" edges to the Rental entity.
func (_c *UserCreate) AddRentals(v ...*Rental) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].Id
	}
	return _c.AddRentalsIds(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != _node.Id {
		id := _spec.Id.Value.(int64)
		_node.Id = int(id)
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = id
	}
	if nodes := _c.mutation.PetsIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PetsTable,
			Columns: []string{user.PetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(pet.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ParentTable,
			Columns: []string{user.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChildrenTable,
			Columns: []string{user.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SpouseIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SpouseTable,
			Columns: []string{user.SpouseColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(user.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SpouseId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CardIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.CardTable,
			Columns: []string{user.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(card.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MetadataIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.MetadataTable,
			Columns: []string{user.MetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(metadata.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InfoIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.InfoTable,
			Columns: []string{user.InfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(info.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RentalsIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RentalsTable,
			Columns: []string{user.RentalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(rental.FieldId, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				if specs[i].Id.Value != nil && nodes[i].Id == 0 {
					id := specs[i].Id.Value.(int64)
					nodes[i].Id = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
