// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package card

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/entc/integration/edgefield/ent/predicate"
)

// Id filters vertices based on their Id field.
func Id(id int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id int) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...int) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...int) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id int) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id int) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id int) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id int) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldId, id))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldNumber, v))
}

// OwnerId applies equality check predicate on the "owner_id" field. It's identical to OwnerIdEQ.
func OwnerId(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldOwnerId, v))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v string) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...string) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v string) predicate.Card {
	return predicate.Card(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v string) predicate.Card {
	return predicate.Card(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v string) predicate.Card {
	return predicate.Card(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v string) predicate.Card {
	return predicate.Card(sql.FieldLTE(FieldNumber, v))
}

// NumberContains applies the Contains predicate on the "number" field.
func NumberContains(v string) predicate.Card {
	return predicate.Card(sql.FieldContains(FieldNumber, v))
}

// NumberHasPrefix applies the HasPrefix predicate on the "number" field.
func NumberHasPrefix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasPrefix(FieldNumber, v))
}

// NumberHasSuffix applies the HasSuffix predicate on the "number" field.
func NumberHasSuffix(v string) predicate.Card {
	return predicate.Card(sql.FieldHasSuffix(FieldNumber, v))
}

// NumberIsNil applies the IsNil predicate on the "number" field.
func NumberIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldNumber))
}

// NumberNotNil applies the NotNil predicate on the "number" field.
func NumberNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldNumber))
}

// NumberEqualFold applies the EqualFold predicate on the "number" field.
func NumberEqualFold(v string) predicate.Card {
	return predicate.Card(sql.FieldEqualFold(FieldNumber, v))
}

// NumberContainsFold applies the ContainsFold predicate on the "number" field.
func NumberContainsFold(v string) predicate.Card {
	return predicate.Card(sql.FieldContainsFold(FieldNumber, v))
}

// OwnerIdEQ applies the EQ predicate on the "owner_id" field.
func OwnerIdEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldEQ(FieldOwnerId, v))
}

// OwnerIdNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIdNEQ(v int) predicate.Card {
	return predicate.Card(sql.FieldNEQ(FieldOwnerId, v))
}

// OwnerIdIn applies the In predicate on the "owner_id" field.
func OwnerIdIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldIn(FieldOwnerId, vs...))
}

// OwnerIdNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIdNotIn(vs ...int) predicate.Card {
	return predicate.Card(sql.FieldNotIn(FieldOwnerId, vs...))
}

// OwnerIdIsNil applies the IsNil predicate on the "owner_id" field.
func OwnerIdIsNil() predicate.Card {
	return predicate.Card(sql.FieldIsNull(FieldOwnerId))
}

// OwnerIdNotNil applies the NotNil predicate on the "owner_id" field.
func OwnerIdNotNil() predicate.Card {
	return predicate.Card(sql.FieldNotNull(FieldOwnerId))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Card {
	return predicate.Card(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Card) predicate.Card {
	return predicate.Card(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Card) predicate.Card {
	return predicate.Card(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Card) predicate.Card {
	return predicate.Card(sql.NotPredicates(p))
}
