// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"uuid"

	"entgo.io/ent/entc/integration/stduuid/ent/schema"
	"entgo.io/ent/entc/integration/stduuid/ent/user"

	"entgo.io/ent/schema/field"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescRef is the schema descriptor for ref field.
	userDescRef := userFields[2].Descriptor()
	user.ValueScanner.Ref = userDescRef.ValueScanner.(field.TypeValueScanner[uuid.UUID])
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	user.ValueScanner.ID = userDescID.ValueScanner.(field.TypeValueScanner[uuid.UUID])
}
