// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"uuid"

	"github.com/protobuf-orm/ent/entc/integration/stduuid/ent/schema"
	"github.com/protobuf-orm/ent/entc/integration/stduuid/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescId is the schema descriptor for id field.
	userDescId := userFields[0].Descriptor()
	// user.DefaultId holds the default value on creation for the id field.
	user.DefaultId = userDescId.Default.(func() uuid.UUID)
}
