// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package link

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/entc/integration/customid/ent/schema"
	uuidc "github.com/protobuf-orm/ent/entc/integration/customid/uuidcompatible"
)

const (
	// Label holds the string label denoting the link type in the database.
	Label = "link"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldLinkInformation holds the string denoting the link_information field in the database.
	FieldLinkInformation = "link_information"
	// Table holds the table name of the link in the database.
	Table = "link"
)

// Columns holds all Sql columns for link fields.
var Columns = []string{
	FieldId,
	FieldLinkInformation,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLinkInformation holds the default value on creation for the "link_information" field.
	DefaultLinkInformation map[string]schema.LinkInformation
	// DefaultId holds the default value on creation for the "id" field.
	DefaultId func() uuidc.UuidC
)

// OrderOption defines the ordering options for the Link queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}
