// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package internal

const IncrementStarts = "{\"api\":12884901888,\"builder\":17179869184,\"card\":21474836480,\"comment\":25769803776,\"ex_value_scan\":30064771072,\"field_type\":34359738368,\"file\":38654705664,\"file_type\":42949672960,\"goods\":47244640256,\"group\":51539607552,\"group_info\":55834574848,\"item\":60129542144,\"license\":64424509440,\"node\":68719476736,\"pc\":73014444032,\"pet\":77309411328,\"spec\":81604378624,\"task\":85899345920,\"user\":8589934592}"
