// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"github.com/protobuf-orm/ent/dialect/sql/schema"
	"github.com/protobuf-orm/ent/schema/field"
)

var (
	// PetColumns holds the columns for the "pet" table.
	PetColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// PetTable holds the schema information for the "pet" table.
	PetTable = &schema.Table{
		Name:       "pet",
		Columns:    PetColumns,
		PrimaryKey: []*schema.Column{PetColumns[0]},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "public_info", Type: field.TypeString},
		{Name: "private_info", Type: field.TypeString},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PetTable,
		UserTable,
	}
)

func init() {
}
