// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package bloblink

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/entc/integration/customid/ent/predicate"
)

// Mutation represents an operation that mutates the BlobLink nodes in the graph.
type Mutation struct {
	op            ent.Op
	typ           string
	created_at    *time.Time
	clearedFields map[string]struct{}
	blob          *uuid.UUID
	clearedblob   bool
	link          *uuid.UUID
	clearedlink   bool
	predicates    []predicate.BlobLink
}

// NewMutation creates a new Mutation for the BlobLink entity.
func NewMutation(op ent.Op) *Mutation {
	return &Mutation{
		op:            op,
		typ:           "BlobLink",
		clearedFields: make(map[string]struct{}),
	}
}

// Predicates returns the list of predicates set on the mutation.
func (m *Mutation) Predicates() []predicate.BlobLink {
	return m.predicates
}

// SetCreatedAt sets the "created_at" field.
func (m *Mutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *Mutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *Mutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetBlobId sets the "blob_id" field.
func (m *Mutation) SetBlobId(u uuid.UUID) {
	m.blob = &u
}

// BlobId returns the value of the "blob_id" field in the mutation.
func (m *Mutation) BlobId() (r uuid.UUID, exists bool) {
	v := m.blob
	if v == nil {
		return
	}
	return *v, true
}

// ResetBlobId resets all changes to the "blob_id" field.
func (m *Mutation) ResetBlobId() {
	m.blob = nil
}

// SetLinksId sets the "links_id" field.
func (m *Mutation) SetLinksId(u uuid.UUID) {
	m.link = &u
}

// LinksId returns the value of the "links_id" field in the mutation.
func (m *Mutation) LinksId() (r uuid.UUID, exists bool) {
	v := m.link
	if v == nil {
		return
	}
	return *v, true
}

// ResetLinksId resets all changes to the "links_id" field.
func (m *Mutation) ResetLinksId() {
	m.link = nil
}

// ClearBlob clears the "blob" edge to the Blob entity.
func (m *Mutation) ClearBlob() {
	m.clearedblob = true
	m.clearedFields[FieldBlobId] = struct{}{}
}

// BlobCleared reports if the "blob" edge to the Blob entity was cleared.
func (m *Mutation) BlobCleared() bool {
	return m.clearedblob
}

// BlobIds returns the "blob" edge Ids in the mutation.
// Note that Ids always returns len(Ids) <= 1 for unique edges, and you should use
// BlobId instead. It exists only for internal usage by the builders.
func (m *Mutation) BlobIds() (ids []uuid.UUID) {
	if id := m.blob; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetBlob resets all changes to the "blob" edge.
func (m *Mutation) ResetBlob() {
	m.blob = nil
	m.clearedblob = false
}

// SetLinkId sets the "link" edge to the Blob entity by id.
func (m *Mutation) SetLinkId(id uuid.UUID) {
	m.link = &id
}

// ClearLink clears the "link" edge to the Blob entity.
func (m *Mutation) ClearLink() {
	m.clearedlink = true
	m.clearedFields[FieldLinksId] = struct{}{}
}

// LinkCleared reports if the "link" edge to the Blob entity was cleared.
func (m *Mutation) LinkCleared() bool {
	return m.clearedlink
}

// LinkId returns the "link" edge Id in the mutation.
func (m *Mutation) LinkId() (id uuid.UUID, exists bool) {
	if m.link != nil {
		return *m.link, true
	}
	return
}

// LinkIds returns the "link" edge Ids in the mutation.
// Note that Ids always returns len(Ids) <= 1 for unique edges, and you should use
// LinkId instead. It exists only for internal usage by the builders.
func (m *Mutation) LinkIds() (ids []uuid.UUID) {
	if id := m.link; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetLink resets all changes to the "link" edge.
func (m *Mutation) ResetLink() {
	m.link = nil
	m.clearedlink = false
}

// Where appends a list predicates to the Mutation builder.
func (m *Mutation) Where(ps ...predicate.BlobLink) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the Mutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *Mutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.BlobLink, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *Mutation) Op() ent.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *Mutation) SetOp(op ent.Op) {
	m.op = op
}

// Type returns the node type of this mutation (BlobLink).
func (m *Mutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *Mutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.created_at != nil {
		fields = append(fields, FieldCreatedAt)
	}
	if m.blob != nil {
		fields = append(fields, FieldBlobId)
	}
	if m.link != nil {
		fields = append(fields, FieldLinksId)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *Mutation) Field(name string) (ent.Value, bool) {
	switch name {
	case FieldCreatedAt:
		return m.CreatedAt()
	case FieldBlobId:
		return m.BlobId()
	case FieldLinksId:
		return m.LinksId()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *Mutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, errors.New("edge schema BlobLink does not support getting old values")
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) SetField(name string, value ent.Value) error {
	switch name {
	case FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case FieldBlobId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBlobId(v)
		return nil
	case FieldLinksId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLinksId(v)
		return nil
	}
	return fmt.Errorf("unknown BlobLink field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *Mutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *Mutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown BlobLink numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *Mutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *Mutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *Mutation) ClearField(name string) error {
	return fmt.Errorf("unknown BlobLink nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *Mutation) ResetField(name string) error {
	switch name {
	case FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case FieldBlobId:
		m.ResetBlobId()
		return nil
	case FieldLinksId:
		m.ResetLinksId()
		return nil
	}
	return fmt.Errorf("unknown BlobLink field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *Mutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.blob != nil {
		edges = append(edges, EdgeBlob)
	}
	if m.link != nil {
		edges = append(edges, EdgeLink)
	}
	return edges
}

// AddedIds returns all Ids (to other nodes) that were added for the given edge
// name in this mutation.
func (m *Mutation) AddedIds(name string) []ent.Value {
	switch name {
	case EdgeBlob:
		if id := m.blob; id != nil {
			return []ent.Value{*id}
		}
	case EdgeLink:
		if id := m.link; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *Mutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIds returns all Ids (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *Mutation) RemovedIds(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *Mutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedblob {
		edges = append(edges, EdgeBlob)
	}
	if m.clearedlink {
		edges = append(edges, EdgeLink)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *Mutation) EdgeCleared(name string) bool {
	switch name {
	case EdgeBlob:
		return m.clearedblob
	case EdgeLink:
		return m.clearedlink
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *Mutation) ClearEdge(name string) error {
	switch name {
	case EdgeBlob:
		m.ClearBlob()
		return nil
	case EdgeLink:
		m.ClearLink()
		return nil
	}
	return fmt.Errorf("unknown BlobLink unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *Mutation) ResetEdge(name string) error {
	switch name {
	case EdgeBlob:
		m.ResetBlob()
		return nil
	case EdgeLink:
		m.ResetLink()
		return nil
	}
	return fmt.Errorf("unknown BlobLink edge %s", name)
}
